-- MySQL Script generated by MySQL Workbench
-- Sat Oct 20 18:33:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `activity` VARCHAR(45) NULL,
  `user_type_id` INT NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `user_type_id`),
  INDEX `fk_user_user_type_idx` (`user_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_user_type`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `mydb`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`object_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`object_type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`objects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`objects` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `object_type_id` INT NOT NULL,
  `open` TINYINT NULL,
  `close` TINYINT NULL,
  `auto` TINYINT NULL,
  PRIMARY KEY (`id`, `object_type_id`),
  INDEX `fk_objects_object_type1_idx` (`object_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_objects_object_type1`
    FOREIGN KEY (`object_type_id`)
    REFERENCES `mydb`.`object_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profiles` (
  `id` INT NOT NULL,
  `profile` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_profiles_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_profiles_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trigger_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trigger_type` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`access` (
  `id` INT NOT NULL,
  `date_of` DATETIME NULL,
  `date_to` DATETIME NULL,
  `opening_counter` INT NULL,
  `way_of_opening` VARCHAR(45) NULL,
  `user_id` INT NULL,
  `objects_id` INT NULL,
  `profiles_id` INT NULL,
  `trigger_type_id` INT NULL,
  PRIMARY KEY (`id`, `user_id`, `objects_id`, `profiles_id`, `trigger_type_id`),
  INDEX `fk_access_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_access_objects1_idx` (`objects_id` ASC) VISIBLE,
  INDEX `fk_access_profiles1_idx` (`profiles_id` ASC) VISIBLE,
  INDEX `fk_access_trigger_type1_idx` (`trigger_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_access_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_access_objects1`
    FOREIGN KEY (`objects_id`)
    REFERENCES `mydb`.`objects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_access_profiles1`
    FOREIGN KEY (`profiles_id`)
    REFERENCES `mydb`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_access_trigger_type1`
    FOREIGN KEY (`trigger_type_id`)
    REFERENCES `mydb`.`trigger_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event_type` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event_log` (
  `id` INT NOT NULL,
  `time` DATETIME NULL,
  `text` VARCHAR(50) NULL,
  `event_type_id` INT NOT NULL,
  `user_id` INT NULL,
  `access_id` INT NOT NULL,
  PRIMARY KEY (`id`, `event_type_id`, `user_id`, `access_id`),
  INDEX `fk_event_log_event_type1_idx` (`event_type_id` ASC) VISIBLE,
  INDEX `fk_event_log_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_event_log_access1_idx` (`access_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_log_event_type1`
    FOREIGN KEY (`event_type_id`)
    REFERENCES `mydb`.`event_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_log_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_log_access1`
    FOREIGN KEY (`access_id`)
    REFERENCES `mydb`.`access` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
